title: 'Deep learning Segmentation: from the scratch'
description: 'In this course we will learn how to use ITK snap to mask for CT scan images. '
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
